spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

    data: classpath:h2/data.sql
    schema: classpath:h2/schema.sql
    #platform: h2

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # (1) 스키마 자동 생성
    properties:
      hibernate:
        format_sql: true
        show-sql: true      # (2) SQL 쿼리 출력
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema.sql

  logging:
    level:
      org.hibernate: info
      org.springframework: info


