CREATE TABLE IF NOT EXISTS USERS (
    USER_ID bigint NOT NULL AUTO_INCREMENT,
    EMAIL varchar(100) NOT NULL UNIQUE,
    USERNAME varchar(100) NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS QUESTION (
    QUESTION_ID bigint NOT NULL AUTO_INCREMENT,
    USER_ID bigint,
    QUESTION_TITLE varchar(100) NOT NULL,
    CONTENT varchar(500) NOT NULL,
    PRIMARY KEY (QUESTION_ID)
    FOREIGN KEY(USERS_ID) REFERENCES USERS(USER_ID)
);

