

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID bigint NOT NULL AUTO_INCREMENT,
    EMAIL varchar(100) NOT NULL UNIQUE,
    USERNAME varchar(100) NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);


CREATE TABLE IF NOT EXISTS QUESTION (
    QUESTION_ID bigint NOT NULL AUTO_INCREMENT,
    USER_ID bigint,
    QUESTION_TITLE varchar(100) NOT NULL,
    CONTENT varchar(500) NOT NULL,
    PRIMARY KEY (QUESTION_ID)
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)

);


CREATE TABLE IF NOT EXISTS QUESTIONTAG (
    QUESTIONTAG_ID bigint NOT NULL AUTO_INCREMENT,
    QUESTION_ID bigint,
    TAG_ID bigint,
    PRIMARY KEY (QUESTIONTAG_ID)
    FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)
    FOREIGN KEY(TAG_ID) REFERENCES TAGS(TAG_ID)
);


CREATE TABLE IF NOT EXISTS TAGS (
    TAG_ID bigint NOT NULL AUTO_INCREMENT,
    TAG_VALUE varchar(100) NOT NULL,
    TAG_INFO varchar(500) NOT NULL,
    PRIMARY KEY (TAG_ID)

);


CREATE TABLE IF NOT EXISTS ANSWERS (
   ANSWER_ID bigint NOT NULL AUTO_INCREMENT,
   USER_ID bigint,
   QUESTION_ID bigint,
   CONTENT varchar(500) NOT NULL,
   PRIMARY KEY (ANSWER_ID)
   FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
   FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(QUESTION_ID)

);

--CREATE TABLE IF NOT EXISTS COMMENTS (

--)





